import type { ContentItem, ContentRow } from "./types";

// Pool of real Pexels portrait images cycled across titles
const P = {
  astronaut1: "https://images.pexels.com/photos/7662473/pexels-photo-7662473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut2: "https://images.pexels.com/photos/7662940/pexels-photo-7662940.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut3: "https://images.pexels.com/photos/7660828/pexels-photo-7660828.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut4: "https://images.pexels.com/photos/7671968/pexels-photo-7671968.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut5: "https://images.pexels.com/photos/7662618/pexels-photo-7662618.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut6: "https://images.pexels.com/photos/7662943/pexels-photo-7662943.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut7: "https://images.pexels.com/photos/7672873/pexels-photo-7672873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  astronaut8: "https://images.pexels.com/photos/7662478/pexels-photo-7662478.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir1: "https://images.pexels.com/photos/104707/pexels-photo-104707.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir2: "https://images.pexels.com/photos/10875022/pexels-photo-10875022.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir3: "https://images.pexels.com/photos/3991996/pexels-photo-3991996.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir4: "https://images.pexels.com/photos/18014799/pexels-photo-18014799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir5: "https://images.pexels.com/photos/5650593/pexels-photo-5650593.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  noir6: "https://images.pexels.com/photos/31591818/pexels-photo-31591818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait1: "https://images.pexels.com/photos/8671511/pexels-photo-8671511.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait2: "https://images.pexels.com/photos/14991299/pexels-photo-14991299.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait3: "https://images.pexels.com/photos/34622355/pexels-photo-34622355.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait4: "https://images.pexels.com/photos/31670098/pexels-photo-31670098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait5: "https://images.pexels.com/photos/35964821/pexels-photo-35964821.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait6: "https://images.pexels.com/photos/29433729/pexels-photo-29433729.png?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait7: "https://images.pexels.com/photos/36086976/pexels-photo-36086976.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait8: "https://images.pexels.com/photos/10040315/pexels-photo-10040315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait9: "https://images.pexels.com/photos/3862604/pexels-photo-3862604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait10: "https://images.pexels.com/photos/14697730/pexels-photo-14697730.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait11: "https://images.pexels.com/photos/16177323/pexels-photo-16177323.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait12: "https://images.pexels.com/photos/37796905/pexels-photo-37796905.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait13: "https://images.pexels.com/photos/32796349/pexels-photo-32796349.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait14: "https://images.pexels.com/photos/17589611/pexels-photo-17589611.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait15: "https://images.pexels.com/photos/29140644/pexels-photo-29140644.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait16: "https://images.pexels.com/photos/31241017/pexels-photo-31241017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait17: "https://images.pexels.com/photos/27722150/pexels-photo-27722150.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  portrait18: "https://images.pexels.com/photos/7744180/pexels-photo-7744180.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier1: "https://images.pexels.com/photos/36654864/pexels-photo-36654864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier2: "https://images.pexels.com/photos/5697207/pexels-photo-5697207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier3: "https://images.pexels.com/photos/30687112/pexels-photo-30687112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier4: "https://images.pexels.com/photos/12551324/pexels-photo-12551324.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier5: "https://images.pexels.com/photos/35248149/pexels-photo-35248149.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier6: "https://images.pexels.com/photos/10895248/pexels-photo-10895248.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier7: "https://images.pexels.com/photos/5697198/pexels-photo-5697198.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  soldier8: "https://images.pexels.com/photos/30042244/pexels-photo-30042244.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero1: "https://images.pexels.com/photos/38691343/pexels-photo-38691343.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero2: "https://images.pexels.com/photos/38691332/pexels-photo-38691332.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero3: "https://images.pexels.com/photos/38691362/pexels-photo-38691362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero4: "https://images.pexels.com/photos/38691331/pexels-photo-38691331.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero5: "https://images.pexels.com/photos/38691365/pexels-photo-38691365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero6: "https://images.pexels.com/photos/38691336/pexels-photo-38691336.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero7: "https://images.pexels.com/photos/38691349/pexels-photo-38691349.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero8: "https://images.pexels.com/photos/38691341/pexels-photo-38691341.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero9: "https://images.pexels.com/photos/38576031/pexels-photo-38576031.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero10: "https://images.pexels.com/photos/38691364/pexels-photo-38691364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero11: "https://images.pexels.com/photos/38691326/pexels-photo-38691326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero12: "https://images.pexels.com/photos/38691333/pexels-photo-38691333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  superhero13: "https://images.pexels.com/photos/38691346/pexels-photo-38691346.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror1: "https://images.pexels.com/photos/3772353/pexels-photo-3772353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror2: "https://images.pexels.com/photos/12360547/pexels-photo-12360547.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror3: "https://images.pexels.com/photos/26612521/pexels-photo-26612521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror4: "https://images.pexels.com/photos/15015851/pexels-photo-15015851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror5: "https://images.pexels.com/photos/18949136/pexels-photo-18949136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror6: "https://images.pexels.com/photos/14075066/pexels-photo-14075066.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror7: "https://images.pexels.com/photos/13316187/pexels-photo-13316187.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  horror8: "https://images.pexels.com/photos/10119143/pexels-photo-10119143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic1: "https://images.pexels.com/photos/24602233/pexels-photo-24602233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic2: "https://images.pexels.com/photos/33807743/pexels-photo-33807743.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic3: "https://images.pexels.com/photos/18206881/pexels-photo-18206881.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic4: "https://images.pexels.com/photos/19448364/pexels-photo-19448364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic5: "https://images.pexels.com/photos/32059122/pexels-photo-32059122.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  romantic6: "https://images.pexels.com/photos/13692477/pexels-photo-13692477.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain1: "https://images.pexels.com/photos/3011825/pexels-photo-3011825.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain2: "https://images.pexels.com/photos/10706115/pexels-photo-10706115.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain3: "https://images.pexels.com/photos/20214934/pexels-photo-20214934.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain4: "https://images.pexels.com/photos/38986732/pexels-photo-38986732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain5: "https://images.pexels.com/photos/12365649/pexels-photo-12365649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain6: "https://images.pexels.com/photos/3986942/pexels-photo-3986942.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car1: "https://images.pexels.com/photos/16007818/pexels-photo-16007818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car2: "https://images.pexels.com/photos/19502011/pexels-photo-19502011.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car3: "https://images.pexels.com/photos/12641797/pexels-photo-12641797.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car4: "https://images.pexels.com/photos/18720557/pexels-photo-18720557.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car5: "https://images.pexels.com/photos/9783510/pexels-photo-9783510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  car6: "https://images.pexels.com/photos/12918283/pexels-photo-12918283.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  flame1: "https://images.pexels.com/photos/8738500/pexels-photo-8738500.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  flame2: "https://images.pexels.com/photos/20385234/pexels-photo-20385234.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  flame3: "https://images.pexels.com/photos/9606890/pexels-photo-9606890.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  flame4: "https://images.pexels.com/photos/14549175/pexels-photo-14549175.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  flame5: "https://images.pexels.com/photos/8991533/pexels-photo-8991533.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  smoke1: "https://images.pexels.com/photos/11839491/pexels-photo-11839491.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  smoke2: "https://images.pexels.com/photos/604672/pexels-photo-604672.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  retro1: "https://images.pexels.com/photos/19153723/pexels-photo-19153723.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  retro2: "https://images.pexels.com/photos/19744212/pexels-photo-19744212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  retro3: "https://images.pexels.com/photos/10194706/pexels-photo-10194706.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  retro4: "https://images.pexels.com/photos/32444060/pexels-photo-32444060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  retro5: "https://images.pexels.com/photos/9560091/pexels-photo-9560091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  neonDiner: "https://images.pexels.com/photos/33611113/pexels-photo-33611113.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  rainNeon: "https://images.pexels.com/photos/19057542/pexels-photo-19057542.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  explosion1: "https://images.pexels.com/photos/5108764/pexels-photo-5108764.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  explosion2: "https://images.pexels.com/photos/35982142/pexels-photo-35982142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema1: "https://images.pexels.com/photos/7991500/pexels-photo-7991500.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema2: "https://images.pexels.com/photos/7991396/pexels-photo-7991396.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema3: "https://images.pexels.com/photos/8263369/pexels-photo-8263369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema4: "https://images.pexels.com/photos/8271461/pexels-photo-8271461.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
};

// Backdrops (landscape) pool
const B = {
  space1: "https://images.pexels.com/photos/29652322/pexels-photo-29652322.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  space2: "https://images.pexels.com/photos/18337644/pexels-photo-18337644.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  city1: "https://images.pexels.com/photos/10875022/pexels-photo-10875022.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  city2: "https://images.pexels.com/photos/18014799/pexels-photo-18014799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  city3: "https://images.pexels.com/photos/5650593/pexels-photo-5650593.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  city4: "https://images.pexels.com/photos/9676248/pexels-photo-9676248.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema1: "https://images.pexels.com/photos/7991500/pexels-photo-7991500.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  cinema2: "https://images.pexels.com/photos/7991396/pexels-photo-7991396.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  explosion1: "https://images.pexels.com/photos/35982142/pexels-photo-35982142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  explosion2: "https://images.pexels.com/photos/5108764/pexels-photo-5108764.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  fog1: "https://images.pexels.com/photos/104707/pexels-photo-104707.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  fog2: "https://images.pexels.com/photos/19501800/pexels-photo-19501800.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain1: "https://images.pexels.com/photos/20214934/pexels-photo-20214934.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  mountain2: "https://images.pexels.com/photos/3011825/pexels-photo-3011825.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  rainNeon: "https://images.pexels.com/photos/35171253/pexels-photo-35171253.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  nightSt: "https://images.pexels.com/photos/31591818/pexels-photo-31591818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
};

const G = ""; // empty string = use gradient poster instead of image

export const CATALOG: ContentItem[] = [
  // === FEATURED ===
  { id: "dune-2", title: "Dune: Part Two", type: "movie", embedId: "tt15239678", year: 2024, rating: "8.5", duration: "2h 46m", genres: ["Sci-Fi", "Adventure", "Drama"], description: "Paul Atreides unites with the Fremen while seeking revenge against the conspirators who destroyed his family.", poster: P.astronaut2, backdrop: B.space1, featured: true },
  { id: "dark-knight", title: "The Dark Knight", type: "movie", embedId: "tt0468569", year: 2008, rating: "9.0", duration: "2h 32m", genres: ["Action", "Crime", "Drama"], description: "Batman must confront the Joker, one of the greatest psychological and physical tests of his ability to fight injustice.", poster: P.portrait1, backdrop: B.city1 },
  { id: "inception", title: "Inception", type: "movie", embedId: "tt1375666", year: 2010, rating: "8.8", duration: "2h 28m", genres: ["Action", "Sci-Fi", "Thriller"], description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", poster: P.noir1, backdrop: B.cinema2 },
  { id: "interstellar", title: "Interstellar", type: "movie", embedId: "tt0816692", year: 2014, rating: "8.7", duration: "2h 49m", genres: ["Adventure", "Drama", "Sci-Fi"], description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster: P.astronaut1, backdrop: B.space1 },
  { id: "the-batman", title: "The Batman", type: "movie", embedId: "tt1877830", year: 2022, rating: "7.8", duration: "2h 56m", genres: ["Action", "Crime", "Mystery"], description: "Batman investigates Gotham's hidden corruption and questions his family's involvement.", poster: P.portrait2, backdrop: B.city2 },
  { id: "br-2049", title: "Blade Runner 2049", type: "movie", embedId: "tt1856101", year: 2017, rating: "8.0", duration: "2h 44m", genres: ["Action", "Drama", "Sci-Fi"], description: "K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.", poster: P.astronaut3, backdrop: B.space2 },
  { id: "joker", title: "Joker", type: "movie", embedId: "tt7286456", year: 2019, rating: "8.4", duration: "2h 2m", genres: ["Crime", "Drama", "Thriller"], description: "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.", poster: P.portrait3, backdrop: B.city3 },
  { id: "mad-max", title: "Mad Max: Fury Road", type: "movie", embedId: "tt1392190", year: 2015, rating: "8.1", duration: "2h 0m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A woman rebels against a tyrannical ruler in a post-apocalyptic wasteland.", poster: P.explosion1, backdrop: B.explosion2 },
  { id: "oppenheimer", title: "Oppenheimer", type: "movie", embedId: "tt15398776", year: 2023, rating: "8.3", duration: "3h 0m", genres: ["Biography", "Drama", "History"], description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb.", poster: P.portrait5, backdrop: B.cinema1 },
  { id: "matrix", title: "The Matrix", type: "movie", embedId: "tt0133093", year: 1999, rating: "8.7", duration: "2h 16m", genres: ["Action", "Sci-Fi"], description: "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.", poster: P.portrait9, backdrop: B.city1 },
  { id: "parasite", title: "Parasite", type: "movie", embedId: "tt6751668", year: 2019, rating: "8.5", duration: "2h 12m", genres: ["Drama", "Thriller"], description: "Greed and class discrimination threaten the symbiotic relationship between the wealthy Park family and the destitute Kim clan.", poster: P.noir6, backdrop: B.nightSt },
  { id: "john-wick-1", title: "John Wick", type: "movie", embedId: "tt2911666", year: 2014, rating: "7.4", duration: "1h 41m", genres: ["Action", "Crime", "Thriller"], description: "An ex-hitman comes out of retirement to track down the gangsters who killed his dog and stole his car.", poster: P.portrait7, backdrop: B.city3 },
  { id: "john-wick-2", title: "John Wick: Chapter 2", type: "movie", embedId: "tt4425200", year: 2017, rating: "7.4", duration: "2h 2m", genres: ["Action", "Crime", "Thriller"], description: "John Wick is forced to back out of retirement by a former associate plotting to seize control of a shadowy international assassins' guild.", poster: P.portrait4, backdrop: B.fog1 },
  { id: "john-wick-3", title: "John Wick: Chapter 3 - Parabellum", type: "movie", embedId: "tt6148156", year: 2019, rating: "7.4", duration: "2h 11m", genres: ["Action", "Crime", "Thriller"], description: "John Wick is on the run after killing a member of the international assassins' guild.", poster: P.flame3, backdrop: B.explosion1 },
  { id: "john-wick-4", title: "John Wick: Chapter 4", type: "movie", embedId: "tt10366206", year: 2023, rating: "7.7", duration: "2h 49m", genres: ["Action", "Crime", "Thriller"], description: "John Wick uncovers a path to defeating The High Table by taking on its most lethal enemies.", poster: P.flame1, backdrop: B.city2 },

  // === ACTION / BLOCKBUSTERS ===
  { id: "avengers-1", title: "The Avengers", type: "movie", embedId: "tt0848228", year: 2012, rating: "8.0", duration: "2h 23m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Earth's mightiest heroes must come together to stop the mischievous Loki and his alien army.", poster: P.superhero7, backdrop: B.city1 },
  { id: "avengers-ultron", title: "Avengers: Age of Ultron", type: "movie", embedId: "tt2395427", year: 2015, rating: "7.3", duration: "2h 21m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Tony Stark creates an AI system that goes rogue and threatens humanity.", poster: P.superhero3, backdrop: B.city2 },
  { id: "avengers-iw", title: "Avengers: Infinity War", type: "movie", embedId: "tt4154756", year: 2018, rating: "8.4", duration: "2h 29m", genres: ["Action", "Adventure", "Sci-Fi"], description: "The Avengers fight to stop Thanos from collecting all six Infinity Stones.", poster: P.superhero1, backdrop: B.space2 },
  { id: "avengers-eg", title: "Avengers: Endgame", type: "movie", embedId: "tt4154796", year: 2019, rating: "8.4", duration: "3h 1m", genres: ["Action", "Adventure", "Sci-Fi"], description: "The Avengers assemble once more to undo Thanos's actions and restore order.", poster: P.superhero2, backdrop: B.explosion1 },
  { id: "iron-man-1", title: "Iron Man", type: "movie", embedId: "tt0371746", year: 2008, rating: "7.9", duration: "2h 6m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A billionaire industrialist builds a suit of armor to save the world.", poster: P.superhero5, backdrop: B.city3 },
  { id: "iron-man-2", title: "Iron Man 2", type: "movie", embedId: "tt1228705", year: 2010, rating: "7.0", duration: "2h 4m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Tony Stark faces pressure from the government and a new enemy.", poster: P.superhero6, backdrop: B.city1 },
  { id: "iron-man-3", title: "Iron Man 3", type: "movie", embedId: "tt1300854", year: 2013, rating: "7.1", duration: "2h 10m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Tony Stark confronts a powerful enemy whose reach knows no bounds.", poster: P.superhero8, backdrop: B.explosion2 },
  { id: "cap-1", title: "Captain America: The First Avenger", type: "movie", embedId: "tt0458339", year: 2011, rating: "6.9", duration: "2h 4m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Steve Rogers volunteers for a top secret research project that turns him into Captain America.", poster: P.superhero4, backdrop: B.cinema1 },
  { id: "cap-winter", title: "Captain America: The Winter Soldier", type: "movie", embedId: "tt1843866", year: 2014, rating: "7.7", duration: "2h 16m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Captain America teams with Black Widow to uncover a conspiracy.", poster: P.superhero11, backdrop: B.fog1 },
  { id: "cap-civil", title: "Captain America: Civil War", type: "movie", embedId: "tt3498820", year: 2016, rating: "7.8", duration: "2h 27m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Political pressure causes the Avengers to split into two factions.", poster: P.superhero9, backdrop: B.city2 },
  { id: "thor-1", title: "Thor", type: "movie", embedId: "tt0800369", year: 2011, rating: "7.0", duration: "1h 55m", genres: ["Action", "Adventure", "Fantasy"], description: "The powerful but arrogant god Thor is cast out of Asgard.", poster: P.superhero10, backdrop: B.space1 },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", type: "movie", embedId: "tt3501632", year: 2017, rating: "7.9", duration: "2h 10m", genres: ["Action", "Adventure", "Comedy"], description: "Thor is imprisoned and must race against time to save Asgard.", poster: P.superhero12, backdrop: B.space2 },
  { id: "guardians-1", title: "Guardians of the Galaxy", type: "movie", embedId: "tt2015381", year: 2014, rating: "8.0", duration: "2h 1m", genres: ["Action", "Adventure", "Comedy"], description: "A group of intergalactic criminals must pull together to stop a fanatic.", poster: P.astronaut4, backdrop: B.space1 },
  { id: "guardians-2", title: "Guardians of the Galaxy Vol. 2", type: "movie", embedId: "tt3896198", year: 2017, rating: "7.6", duration: "2h 16m", genres: ["Action", "Adventure", "Comedy"], description: "The Guardians discover the mystery of Peter Quill's parentage.", poster: P.astronaut5, backdrop: B.space2 },
  { id: "black-panther", title: "Black Panther", type: "movie", embedId: "tt1825683", year: 2018, rating: "7.3", duration: "2h 14m", genres: ["Action", "Adventure", "Sci-Fi"], description: "T'Challa returns home to Wakanda to take his rightful place as king.", poster: P.superhero13, backdrop: B.cinema2 },
  { id: "spiderman-home", title: "Spider-Man: Homecoming", type: "movie", embedId: "tt4633694", year: 2017, rating: "7.4", duration: "2h 13m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Peter Parker balances high school life with being Spider-Man.", poster: P.superhero7, backdrop: B.city3 },
  { id: "spiderman-ffh", title: "Spider-Man: Far From Home", type: "movie", embedId: "tt9686112", year: 2019, rating: "7.5", duration: "2h 9m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Spider-Man joins school trip to Europe and faces new threats.", poster: P.superhero12, backdrop: B.city1 },
  { id: "spiderman-nwh", title: "Spider-Man: No Way Home", type: "movie", embedId: "tt10872600", year: 2021, rating: "8.2", duration: "2h 28m", genres: ["Action", "Adventure", "Sci-Fi"], description: "Spider-Man asks Doctor Strange for help and opens the multiverse.", poster: P.superhero3, backdrop: B.space2 },
  { id: "doctor-strange", title: "Doctor Strange", type: "movie", embedId: "tt1211837", year: 2016, rating: "7.5", duration: "1h 55m", genres: ["Action", "Adventure", "Fantasy"], description: "A surgeon discovers the world of mystic arts after a career-ending accident.", poster: P.astronaut6, backdrop: B.space1 },
  { id: "wakanda-forever", title: "Black Panther: Wakanda Forever", type: "movie", embedId: "tt9114286", year: 2022, rating: "7.3", duration: "2h 41m", genres: ["Action", "Adventure", "Drama"], description: "The people of Wakanda fight to protect their nation from intervening world powers.", poster: P.superhero1, backdrop: B.cinema1 },

  // === CHRISTOPHER NOLAN ===
  { id: "tenet", title: "Tenet", type: "movie", embedId: "tt6723592", year: 2020, rating: "7.3", duration: "2h 30m", genres: ["Action", "Sci-Fi", "Thriller"], description: "A secret agent manipulates the flow of time to prevent World War III.", poster: P.portrait12, backdrop: B.city1 },
  { id: "memento", title: "Memento", type: "movie", embedId: "tt0209144", year: 2000, rating: "8.4", duration: "1h 53m", genres: ["Mystery", "Thriller", "Drama"], description: "A man with short-term memory loss attempts to track down his wife's murderer.", poster: P.noir3, backdrop: B.fog1 },
  { id: "prestige", title: "The Prestige", type: "movie", embedId: "tt0482571", year: 2006, rating: "8.5", duration: "2h 10m", genres: ["Drama", "Mystery", "Thriller"], description: "Two rival magicians engage in a bitter and deadly competition.", poster: P.portrait6, backdrop: B.cinema2 },
  { id: "batman-begins", title: "Batman Begins", type: "movie", embedId: "tt0372784", year: 2005, rating: "8.2", duration: "2h 32m", genres: ["Action", "Crime", "Drama"], description: "Bruce Wayne begins his training to become the Dark Knight.", poster: P.portrait1, backdrop: B.city2 },
  { id: "dark-knight-rises", title: "The Dark Knight Rises", type: "movie", embedId: "tt1345836", year: 2012, rating: "8.4", duration: "2h 44m", genres: ["Action", "Crime", "Drama"], description: "Batman rises to save Gotham from Bane's army.", poster: P.portrait13, backdrop: B.city3 },
  { id: "dunkirk", title: "Dunkirk", type: "movie", embedId: "tt5013056", year: 2017, rating: "7.8", duration: "1h 46m", genres: ["Action", "Drama", "History"], description: "Allied soldiers are surrounded by the German army and must be evacuated.", poster: P.soldier2, backdrop: B.mountain1 },
  { id: "following", title: "Following", type: "movie", embedId: "tt0154506", year: 1998, rating: "7.5", duration: "1h 9m", genres: ["Crime", "Mystery", "Thriller"], description: "A young writer follows strangers and becomes entangled in a criminal underworld.", poster: P.noir4, backdrop: B.fog2 },

  // === MARTIN SCORSESE ===
  { id: "goodfellas", title: "Goodfellas", type: "movie", embedId: "tt0099685", year: 1990, rating: "8.7", duration: "2h 25m", genres: ["Biography", "Crime", "Drama"], description: "The story of Henry Hill and his life in the mob.", poster: P.portrait5, backdrop: B.city3 },
  { id: "taxi-driver", title: "Taxi Driver", type: "movie", embedId: "tt0075314", year: 1976, rating: "8.2", duration: "1h 54m", genres: ["Crime", "Drama"], description: "A mentally unstable veteran works as a taxi driver in NYC.", poster: P.noir2, backdrop: B.rainNeon },
  { id: "casino", title: "Casino", type: "movie", embedId: "tt0112641", year: 1995, rating: "8.2", duration: "2h 58m", genres: ["Crime", "Drama"], description: "A tale of greed, deception, money, power, and murder in Las Vegas.", poster: P.retro3, backdrop: B.cinema1 },
  { id: "the-departed", title: "The Departed", type: "movie", embedId: "tt0407887", year: 2006, rating: "8.5", duration: "2h 31m", genres: ["Crime", "Drama", "Thriller"], description: "An undercover cop and a mole in the police try to identify each other.", poster: P.portrait14, backdrop: B.city1 },
  { id: "shutter-island", title: "Shutter Island", type: "movie", embedId: "tt1130884", year: 2010, rating: "8.2", duration: "2h 18m", genres: ["Mystery", "Thriller", "Drama"], description: "A U.S. Marshal investigates the disappearance of a patient at a hospital for the criminally insane.", poster: P.horror4, backdrop: B.fog2 },
  { id: "irishman", title: "The Irishman", type: "movie", embedId: "tt1302006", year: 2019, rating: "7.8", duration: "3h 29m", genres: ["Biography", "Crime", "Drama"], description: "An aging hitman recalls his time with the mob and his alleged involvement with the slaying of Jimmy Hoffa.", poster: P.portrait16, backdrop: B.city2 },

  // === QUENTIN TARANTINO ===
  { id: "pulp-fiction", title: "Pulp Fiction", type: "movie", embedId: "tt0110912", year: 1994, rating: "8.9", duration: "2h 34m", genres: ["Crime", "Drama"], description: "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine.", poster: P.portrait11, backdrop: B.cinema1 },
  { id: "django", title: "Django Unchained", type: "movie", embedId: "tt1853728", year: 2012, rating: "8.5", duration: "2h 45m", genres: ["Drama", "Western"], description: "A freed slave sets out to rescue his wife from a brutal plantation owner.", poster: P.portrait15, backdrop: B.fog1 },
  { id: "kill-bill-1", title: "Kill Bill: Vol. 1", type: "movie", embedId: "tt0266697", year: 2003, rating: "8.2", duration: "1h 51m", genres: ["Action", "Crime", "Thriller"], description: "The Bride wakens from a four-year coma and seeks vengeance.", poster: P.portrait7, backdrop: B.explosion1 },
  { id: "kill-bill-2", title: "Kill Bill: Vol. 2", type: "movie", embedId: "tt0378194", year: 2004, rating: "8.0", duration: "2h 17m", genres: ["Action", "Crime", "Thriller"], description: "The Bride continues her quest for vengeance against her former boss.", poster: P.portrait8, backdrop: B.fog2 },
  { id: "inglourious", title: "Inglourious Basterds", type: "movie", embedId: "tt0361748", year: 2009, rating: "8.4", duration: "2h 33m", genres: ["Adventure", "Drama", "War"], description: "A Jewish cinema owner and a group of American soldiers plot to assassinate Nazi leaders.", poster: P.soldier1, backdrop: B.cinema2 },
  { id: "hateful-eight", title: "The Hateful Eight", type: "movie", embedId: "tt3460252", year: 2015, rating: "7.8", duration: "2h 57m", genres: ["Drama", "Mystery", "Western"], description: "Bounty hunters seek shelter from a blizzard and get caught in a plot of betrayal.", poster: P.soldier5, backdrop: B.mountain1 },
  { id: "once-upon-hollywood", title: "Once Upon a Time in Hollywood", type: "movie", embedId: "tt7131622", year: 2019, rating: "7.6", duration: "2h 41m", genres: ["Drama", "Comedy"], description: "A faded actor and his stunt double navigate 1969 Hollywood.", poster: P.retro1, backdrop: B.cinema1 },

  // === CLASSICS / CRITICALLY ACCLAIMED ===
  { id: "godfather", title: "The Godfather", type: "movie", embedId: "tt0068646", year: 1972, rating: "9.2", duration: "2h 55m", genres: ["Crime", "Drama"], description: "The aging patriarch of an organized crime dynasty transfers control to his son.", poster: P.portrait6, backdrop: B.cinema1 },
  { id: "godfather-2", title: "The Godfather Part II", type: "movie", embedId: "tt0071562", year: 1974, rating: "9.0", duration: "3h 22m", genres: ["Crime", "Drama"], description: "The early life of Vito Corleone and the story of his son Michael.", poster: P.portrait5, backdrop: B.cinema2 },
  { id: "shawshank", title: "The Shawshank Redemption", type: "movie", embedId: "tt0111161", year: 1994, rating: "9.3", duration: "2h 22m", genres: ["Drama"], description: "Two imprisoned men bond over years, finding solace and eventual redemption.", poster: P.noir4, backdrop: B.fog1 },
  { id: "forrest-gump", title: "Forrest Gump", type: "movie", embedId: "tt0109830", year: 1994, rating: "8.8", duration: "2h 22m", genres: ["Drama", "Romance"], description: "The presidencies of Kennedy and Johnson, the Vietnam War, and more through the eyes of an Alabama man.", poster: P.romantic1, backdrop: B.mountain2 },
  { id: "fight-club", title: "Fight Club", type: "movie", embedId: "tt0137523", year: 1999, rating: "8.8", duration: "2h 19m", genres: ["Drama"], description: "An office employee and a soap maker build a global organization of club fights.", poster: P.portrait4, backdrop: B.city3 },
  { id: "pulp-2", title: "The Wolf of Wall Street", type: "movie", embedId: "tt0993840", year: 2013, rating: "8.2", duration: "3h 0m", genres: ["Biography", "Crime", "Drama"], description: "Based on the true story of Jordan Belfort, a stockbroker who committed fraud.", poster: P.portrait14, backdrop: B.city1 },
  { id: "schindlers-list", title: "Schindler's List", type: "movie", embedId: "tt0108950", year: 1993, rating: "9.0", duration: "3h 15m", genres: ["Biography", "Drama", "History"], description: "A businessman saves the lives of over a thousand Jewish refugees during the Holocaust.", poster: P.noir1, backdrop: B.cinema1 },
  { id: "silence-lambs", title: "The Silence of the Lambs", type: "movie", embedId: "tt0102926", year: 1991, rating: "8.6", duration: "1h 58m", genres: ["Crime", "Drama", "Thriller"], description: "A young FBI cadet seeks help from a cannibalistic serial killer to catch another killer.", poster: P.horror3, backdrop: B.fog1 },
  { id: "se7en", title: "Se7en", type: "movie", embedId: "tt0114369", year: 1995, rating: "8.6", duration: "2h 7m", genres: ["Crime", "Drama", "Mystery"], description: "Two detectives hunt a serial killer who uses the seven deadly sins as motives.", poster: P.noir5, backdrop: B.rainNeon },
  { id: "the-thing", title: "The Thing", type: "movie", embedId: "tt0084787", year: 1982, rating: "8.2", duration: "1h 49m", genres: ["Horror", "Mystery", "Sci-Fi"], description: "Researchers in Antarctica are stalked by a parasitic alien.", poster: P.horror2, backdrop: B.mountain1 },
  { id: "gladiator", title: "Gladiator", type: "movie", embedId: "tt0172495", year: 2000, rating: "8.5", duration: "2h 35m", genres: ["Action", "Adventure", "Drama"], description: "A betrayed Roman general rises through the gladiatorial arena to avenge his family.", poster: P.soldier5, backdrop: B.cinema2 },
  { id: "saving-ryan", title: "Saving Private Ryan", type: "movie", embedId: "tt0120815", year: 1998, rating: "8.6", duration: "2h 49m", genres: ["Drama", "War"], description: "A squad of soldiers goes behind enemy lines to retrieve a paratrooper.", poster: P.soldier3, backdrop: B.mountain2 },
  { id: "apocalypse-now", title: "Apocalypse Now", type: "movie", embedId: "tt0078788", year: 1979, rating: "8.4", duration: "2h 33m", genres: ["Drama", "War"], description: "A captain is sent into the Cambodian jungle to assassinate a renegade colonel.", poster: P.soldier4, backdrop: B.fog2 },
  { id: "full-metal", title: "Full Metal Jacket", type: "movie", embedId: "tt0093058", year: 1987, rating: "8.3", duration: "1h 56m", genres: ["Drama", "War"], description: "A pragmatic Marine observes the dehumanizing effects of the Vietnam War.", poster: P.soldier8, backdrop: B.city3 },

  // === SCI-FI / FANTASY ===
  { id: "arrival", title: "Arrival", type: "movie", embedId: "tt2543164", year: 2016, rating: "7.9", duration: "1h 56m", genres: ["Drama", "Sci-Fi"], description: "A linguist works with the military to communicate with alien visitors.", poster: P.astronaut7, backdrop: B.space1 },
  { id: "gravity", title: "Gravity", type: "movie", embedId: "tt1454468", year: 2013, rating: "7.7", duration: "1h 31m", genres: ["Drama", "Sci-Fi", "Thriller"], description: "Two astronauts work together to survive after an accident leaves them stranded in space.", poster: P.astronaut8, backdrop: B.space2 },
  { id: "the-martian", title: "The Martian", type: "movie", embedId: "tt3659388", year: 2015, rating: "8.0", duration: "2h 24m", genres: ["Adventure", "Drama", "Sci-Fi"], description: "An astronaut becomes stranded on Mars and must find a way to survive.", poster: P.astronaut1, backdrop: B.space1 },
  { id: "prometheus", title: "Prometheus", type: "movie", embedId: "tt1446714", year: 2012, rating: "7.0", duration: "2h 4m", genres: ["Adventure", "Mystery", "Sci-Fi"], description: "A team explores an ancient civilization and discovers a threat to humanity.", poster: P.astronaut3, backdrop: B.space2 },
  { id: "alien-covenant", title: "Alien: Covenant", type: "movie", embedId: "tt2316204", year: 2017, rating: "6.4", duration: "2h 2m", genres: ["Horror", "Sci-Fi"], description: "The crew of a colony ship discovers an uncharted paradise with a terrifying threat.", poster: P.horror6, backdrop: B.space1 },
  { id: "edge-tomorrow", title: "Edge of Tomorrow", type: "movie", embedId: "tt1631867", year: 2014, rating: "7.9", duration: "1h 53m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A soldier fighting aliens relives the same day over and over.", poster: P.soldier6, backdrop: B.explosion1 },
  { id: "district-9", title: "District 9", type: "movie", embedId: "tt1136608", year: 2009, rating: "7.9", duration: "1h 52m", genres: ["Action", "Sci-Fi", "Thriller"], description: "An alien race forced to live in slum-like conditions on Earth finds a friend in a government agent.", poster: P.astronaut4, backdrop: B.city2 },
  { id: "looper", title: "Looper", type: "movie", embedId: "tt1276104", year: 2012, rating: "7.4", duration: "1h 59m", genres: ["Action", "Crime", "Sci-Fi"], description: "A hitman who kills people sent back in time faces a target he can't kill: himself.", poster: P.portrait12, backdrop: B.city1 },
  { id: "oblivion", title: "Oblivion", type: "movie", embedId: "tt1483013", year: 2013, rating: "7.0", duration: "2h 4m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A veteran assigned to extract Earth's remaining resources discovers a shocking truth.", poster: P.astronaut2, backdrop: B.space1 },
  { id: "snowpiercer", title: "Snowpiercer", type: "movie", embedId: "tt1706620", year: 2013, rating: "7.1", duration: "2h 6m", genres: ["Action", "Drama", "Sci-Fi"], description: "Humanity's survivors live on a train that never stops in a frozen world.", poster: P.mountain6, backdrop: B.mountain1 },
  { id: "sunshine", title: "Sunshine", type: "movie", embedId: "tt0448134", year: 2007, rating: "7.2", duration: "1h 47m", genres: ["Adventure", "Sci-Fi", "Thriller"], description: "A team of astronauts is sent to re-ignite the dying sun.", poster: P.flame2, backdrop: B.space2 },

  // === THRILLER / CRIME ===
  { id: "gone-girl", title: "Gone Girl", type: "movie", embedId: "tt2267998", year: 2014, rating: "8.1", duration: "2h 29m", genres: ["Drama", "Mystery", "Thriller"], description: "A man becomes the prime suspect when his wife goes missing.", poster: P.portrait10, backdrop: B.city3 },
  { id: "prisoners", title: "Prisoners", type: "movie", embedId: "tt1392214", year: 2013, rating: "8.2", duration: "2h 33m", genres: ["Crime", "Drama", "Mystery"], description: "A father searches for his missing daughter as the police fail to find clues.", poster: P.horror5, backdrop: B.fog1 },
  { id: "no-country", title: "No Country for Old Men", type: "movie", embedId: "tt0477348", year: 2007, rating: "8.2", duration: "2h 2m", genres: ["Crime", "Drama", "Thriller"], description: "A hunter's life takes a drastic turn when he discovers two million dollars.", poster: P.noir2, backdrop: B.fog2 },
  { id: "zodiac", title: "Zodiac", type: "movie", embedId: "tt0443706", year: 2007, rating: "7.7", duration: "2h 37m", genres: ["Crime", "Drama", "Mystery"], description: "Cartoonist Robert Graysmith becomes obsessed with tracking down the Zodiac killer.", poster: P.portrait16, backdrop: B.city1 },
  { id: "prisoners-2", title: "The Departed", type: "movie", embedId: "tt0407887", year: 2006, rating: "8.5", duration: "2h 31m", genres: ["Crime", "Drama", "Thriller"], description: "An undercover cop and a mole try to identify each other while infiltrating an Irish gang.", poster: P.portrait17, backdrop: B.city2 },
  { id: "heat", title: "Heat", type: "movie", embedId: "tt0113277", year: 1995, rating: "8.3", duration: "2h 50m", genres: ["Crime", "Drama", "Thriller"], description: "A group of bank robbers find their $12 million plan interrupted by a detective.", poster: P.portrait13, backdrop: B.city3 },
  { id: "fargo", title: "Fargo", type: "movie", embedId: "tt0116282", year: 1996, rating: "8.1", duration: "1h 38m", genres: ["Crime", "Drama", "Thriller"], description: "A pregnant police chief investigates a series of homicides in Minnesota.", poster: P.horror1, backdrop: B.fog1 },
  { id: "revenant", title: "The Revenant", type: "movie", embedId: "tt1663202", year: 2015, rating: "8.0", duration: "2h 36m", genres: ["Action", "Adventure", "Drama"], description: "A frontiersman fights for survival after being mauled by a bear.", poster: P.mountain3, backdrop: B.mountain1 },
  { id: "sicario", title: "Sicario", type: "movie", embedId: "tt3397884", year: 2015, rating: "7.6", duration: "2h 1m", genres: ["Action", "Crime", "Drama"], description: "An idealistic FBI agent is enlisted by a government task force to combat the drug trade.", poster: P.soldier7, backdrop: B.city2 },

  // === HORROR ===
  { id: "hereditary", title: "Hereditary", type: "movie", embedId: "tt7784604", year: 2018, rating: "7.3", duration: "2h 7m", genres: ["Drama", "Horror", "Mystery"], description: "A grieving family is haunted by tragedy and a sinister destiny.", poster: P.horror3, backdrop: B.fog2 },
  { id: "conjuring", title: "The Conjuring", type: "movie", embedId: "tt1457767", year: 2013, rating: "7.5", duration: "1h 52m", genres: ["Horror", "Mystery", "Thriller"], description: "Paranormal investigators help a family terrorized by a dark presence.", poster: P.horror4, backdrop: B.fog1 },
  { id: "it-2017", title: "It", type: "movie", embedId: "tt1396484", year: 2017, rating: "7.3", duration: "2h 15m", genres: ["Horror", "Thriller"], description: "Seven children in Maine face a shape-shifting entity known as Pennywise.", poster: P.horror7, backdrop: B.fog2 },
  { id: "get-out", title: "Get Out", type: "movie", embedId: "tt5052448", year: 2017, rating: "7.7", duration: "1h 44m", genres: ["Horror", "Mystery", "Thriller"], description: "A young Black man visits his white girlfriend's family estate and uncovers a disturbing truth.", poster: P.portrait18, backdrop: B.cinema1 },
  { id: "a-quiet-place", title: "A Quiet Place", type: "movie", embedId: "tt6644200", year: 2018, rating: "7.5", duration: "1h 30m", genres: ["Drama", "Horror", "Sci-Fi"], description: "A family struggles to survive in a world full of blind monsters that hunt by sound.", poster: P.horror8, backdrop: B.fog1 },
  { id: "midsommar", title: "Midsommar", type: "movie", embedId: "tt8772262", year: 2019, rating: "7.1", duration: "2h 18m", genres: ["Drama", "Horror", "Mystery"], description: "A couple travels to a rural Swedish village for a midsummer festival that turns sinister.", poster: P.romantic2, backdrop: B.mountain2 },

  // === COMEDY / OTHER ===
  { id: "grand-budapest", title: "The Grand Budapest Hotel", type: "movie", embedId: "tt2278388", year: 2014, rating: "8.1", duration: "1h 39m", genres: ["Comedy", "Drama"], description: "A legendary concierge and his protégé become embroiled in a heist involving a priceless painting.", poster: P.retro4, backdrop: B.cinema2 },
  { id: "wolf-wall-street", title: "The Wolf of Wall Street", type: "movie", embedId: "tt0993840", year: 2013, rating: "8.2", duration: "3h 0m", genres: ["Biography", "Comedy", "Crime"], description: "A stockbroker's rise and fall in the world of Wall Street fraud.", poster: P.car5, backdrop: B.city3 },
  { id: "la-la-land", title: "La La Land", type: "movie", embedId: "tt3783968", year: 2016, rating: "8.0", duration: "2h 8m", genres: ["Comedy", "Drama", "Romance"], description: "A jazz pianist and an aspiring actress fall in love in Los Angeles.", poster: P.romantic5, backdrop: B.city1 },
  { id: "whiplash", title: "Whiplash", type: "movie", embedId: "tt2582802", year: 2014, rating: "8.5", duration: "1h 46m", genres: ["Drama", "Music"], description: "A promising young drummer enrolls at a music conservatory with a ruthless instructor.", poster: P.portrait11, backdrop: B.cinema1 },
  { id: "the-truman-show", title: "The Truman Show", type: "movie", embedId: "tt0120382", year: 1998, rating: "8.2", duration: "1h 42m", genres: ["Comedy", "Drama", "Sci-Fi"], description: "A man discovers his entire life is a reality TV show.", poster: P.portrait15, backdrop: B.city2 },

  // === MORE ACTION / VARIETY ===
  { id: "top-gun-mav", title: "Top Gun: Maverick", type: "movie", embedId: "tt1745960", year: 2022, rating: "8.3", duration: "2h 11m", genres: ["Action", "Drama"], description: "Maverick trains a new group of Top Gun graduates for a dangerous mission.", poster: P.flame4, backdrop: B.explosion1 },
  { id: "mission-impossible-fallout", title: "Mission: Impossible - Fallout", type: "movie", embedId: "tt4912910", year: 2018, rating: "7.7", duration: "2h 27m", genres: ["Action", "Adventure", "Thriller"], description: "Ethan Hunt and his team race against time after a mission goes wrong.", poster: P.soldier6, backdrop: B.city3 },
  { id: "mission-impossible-7", title: "Mission: Impossible - Dead Reckoning", type: "movie", embedId: "tt9603212", year: 2023, rating: "7.6", duration: "2h 43m", genres: ["Action", "Adventure", "Thriller"], description: "Ethan Hunt and his team must track down a terrifying new weapon.", poster: P.car4, backdrop: B.city1 },
  { id: "jurassic-world", title: "Jurassic World", type: "movie", embedId: "tt0369610", year: 2015, rating: "7.0", duration: "2h 4m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A theme park featuring cloned dinosaurs spirals into chaos.", poster: P.mountain4, backdrop: B.mountain1 },
  { id: "avatar", title: "Avatar", type: "movie", embedId: "tt0499549", year: 2009, rating: "7.9", duration: "2h 42m", genres: ["Action", "Adventure", "Fantasy"], description: "A paraplegic Marine becomes torn between following orders and protecting an alien world.", poster: P.astronaut5, backdrop: B.space2 },
  { id: "avatar-2", title: "Avatar: The Way of Water", type: "movie", embedId: "tt1630029", year: 2022, rating: "7.6", duration: "3h 12m", genres: ["Action", "Adventure", "Sci-Fi"], description: "The Sully family seeks refuge with the ocean Metkayina clan.", poster: P.astronaut6, backdrop: B.space1 },
  { id: "top-gun-1", title: "Top Gun", type: "movie", embedId: "tt0092099", year: 1986, rating: "6.9", duration: "1h 50m", genres: ["Action", "Drama"], description: "A hotshot fighter pilot attends an elite Navy training school.", poster: P.flame5, backdrop: B.cinema2 },
  { id: "die-hard", title: "Die Hard", type: "movie", embedId: "tt0095016", year: 1988, rating: "8.2", duration: "2h 12m", genres: ["Action", "Thriller"], description: "An NYPD officer tries to save his wife from terrorists at a Christmas party.", poster: P.explosion2, backdrop: B.city1 },
  { id: "terminator-2", title: "Terminator 2: Judgment Day", type: "movie", embedId: "tt0103064", year: 1991, rating: "8.6", duration: "2h 17m", genres: ["Action", "Sci-Fi"], description: "A cyborg is sent from the future to protect John Connor from a more advanced Terminator.", poster: P.portrait9, backdrop: B.city2 },
  { id: "aliens", title: "Aliens", type: "movie", embedId: "tt0090605", year: 1986, rating: "8.5", duration: "2h 17m", genres: ["Action", "Horror", "Sci-Fi"], description: "Ripley returns to the planet where her crew found the alien.", poster: P.astronaut7, backdrop: B.space1 },
  { id: "predator", title: "Predator", type: "movie", embedId: "tt0093773", year: 1987, rating: "7.8", duration: "1h 47m", genres: ["Action", "Adventure", "Sci-Fi"], description: "A team of commandos are hunted by an extraterrestrial warrior in the jungle.", poster: P.soldier1, backdrop: B.mountain2 },
  { id: "robocop", title: "RoboCop", type: "movie", embedId: "tt0093870", year: 1987, rating: "7.5", duration: "1h 42m", genres: ["Action", "Crime", "Sci-Fi"], description: "A fatally wounded officer returns as a powerful cyborg.", poster: P.superhero8, backdrop: B.city3 },
  { id: "the-fugitive", title: "The Fugitive", type: "movie", embedId: "tt0106977", year: 1993, rating: "7.8", duration: "2h 10m", genres: ["Action", "Crime", "Thriller"], description: "A wrongly convicted man escapes prison and hunts the real killer.", poster: P.portrait17, backdrop: B.city1 },
  { id: "casino-royale", title: "Casino Royale", type: "movie", embedId: "tt0458439", year: 2006, rating: "8.0", duration: "2h 24m", genres: ["Action", "Adventure", "Thriller"], description: "James Bond's first mission as a 007 agent.", poster: P.car1, backdrop: B.city2 },
  { id: "skyfall", title: "Skyfall", type: "movie", embedId: "tt1074638", year: 2012, rating: "7.8", duration: "2h 23m", genres: ["Action", "Adventure", "Thriller"], description: "Bond's loyalty to M is tested as her past returns to haunt her.", poster: P.car3, backdrop: B.city3 },
  { id: "no-time-die", title: "No Time to Die", type: "movie", embedId: "tt2382320", year: 2021, rating: "7.3", duration: "2h 43m", genres: ["Action", "Adventure", "Thriller"], description: "Bond comes out of retirement to face a new villain with dangerous new technology.", poster: P.car6, backdrop: B.city1 },

  // === ANIMATED / FAMILY ===
  { id: "spider-verse", title: "Spider-Man: Into the Spider-Verse", type: "movie", embedId: "tt4633694", year: 2018, rating: "8.4", duration: "1h 57m", genres: ["Animation", "Action", "Adventure"], description: "Teen Miles Morales becomes Spider-Man and joins others from the multiverse.", poster: G, backdrop: B.space2 },
  { id: "up", title: "Up", type: "movie", embedId: "tt1049413", year: 2009, rating: "8.3", duration: "1h 36m", genres: ["Animation", "Adventure", "Comedy"], description: "An elderly widower fulfills his dream by tying balloons to his house.", poster: G, backdrop: B.mountain1 },
  { id: "wall-e", title: "WALL-E", type: "movie", embedId: "tt0910970", year: 2008, rating: "8.4", duration: "1h 38m", genres: ["Animation", "Adventure", "Sci-Fi"], description: "A waste-collecting robot embarks on a journey across space.", poster: G, backdrop: B.space1 },
  { id: "toy-story-3", title: "Toy Story 3", type: "movie", embedId: "tt0435761", year: 2010, rating: "8.3", duration: "1h 43m", genres: ["Animation", "Adventure", "Comedy"], description: "The toys are accidentally donated to a daycare center.", poster: G, backdrop: B.cinema1 },
  { id: "inside-out", title: "Inside Out", type: "movie", embedId: "tt2096673", year: 2015, rating: "8.2", duration: "1h 35m", genres: ["Animation", "Adventure", "Comedy"], description: "The emotions of a young girl guide her through a difficult move.", poster: G, backdrop: B.cinema2 },
  { id: "ratatouille", title: "Ratatouille", type: "movie", embedId: "tt0382932", year: 2007, rating: "8.1", duration: "1h 51m", genres: ["Animation", "Comedy", "Family"], description: "A rat who can cook makes a partnership with a young kitchen worker.", poster: G, backdrop: B.cinema1 },
  { id: "finding-nemo", title: "Finding Nemo", type: "movie", embedId: "tt0266543", year: 2003, rating: "8.2", duration: "1h 40m", genres: ["Animation", "Adventure", "Comedy"], description: "A clownfish searches for his missing son in the ocean.", poster: G, backdrop: B.space2 },
  { id: "the-lion-king", title: "The Lion King", type: "movie", embedId: "tt6105098", year: 2019, rating: "6.8", duration: "1h 58m", genres: ["Animation", "Adventure", "Drama"], description: "A young lion prince flees his kingdom after his father's death.", poster: G, backdrop: B.mountain2 },
  { id: "coco", title: "Coco", type: "movie", embedId: "tt2380307", year: 2017, rating: "8.4", duration: "1h 45m", genres: ["Animation", "Adventure", "Family"], description: "A young boy dreams of becoming a musician and enters the Land of the Dead.", poster: G, backdrop: B.cinema2 },

  // === TV SHOWS ===
  { id: "got", title: "Game of Thrones", type: "tv", embedId: "1399", year: 2011, rating: "9.2", duration: "8 Seasons", genres: ["Action", "Adventure", "Drama"], description: "Nine noble families fight for control over the lands of Westeros.", poster: P.cinema1, backdrop: B.cinema1, seasons: 8 },
  { id: "breaking-bad", title: "Breaking Bad", type: "tv", embedId: "1396", year: 2008, rating: "9.5", duration: "5 Seasons", genres: ["Crime", "Drama", "Thriller"], description: "A chemistry teacher turns to manufacturing meth with a former student.", poster: P.portrait3, backdrop: B.city3, seasons: 5 },
  { id: "stranger-things", title: "Stranger Things", type: "tv", embedId: "60735", year: 2016, rating: "8.7", duration: "4 Seasons", genres: ["Drama", "Fantasy", "Horror"], description: "Kids uncover a mystery involving secret experiments and supernatural forces.", poster: P.portrait8, backdrop: B.cinema1, seasons: 4 },
  { id: "the-witcher", title: "The Witcher", type: "tv", embedId: "71912", year: 2019, rating: "8.0", duration: "3 Seasons", genres: ["Action", "Adventure", "Fantasy"], description: "Geralt of Rivia struggles to find his place in a world of beasts and people.", poster: P.portrait6, backdrop: B.fog1, seasons: 3 },
  { id: "peaky-blinders", title: "Peaky Blinders", type: "tv", embedId: "60574", year: 2013, rating: "8.8", duration: "6 Seasons", genres: ["Crime", "Drama"], description: "A gangster family epic set in 1900s England.", poster: P.portrait4, backdrop: B.fog2, seasons: 6 },
  { id: "the-boys", title: "The Boys", type: "tv", embedId: "76479", year: 2019, rating: "8.7", duration: "4 Seasons", genres: ["Action", "Comedy", "Crime"], description: "Vigilantes take down corrupt superheroes who abuse their abilities.", poster: P.superhero1, backdrop: B.city2, seasons: 4 },
  { id: "wednesday", title: "Wednesday", type: "tv", embedId: "119051", year: 2022, rating: "8.1", duration: "1 Season", genres: ["Comedy", "Crime", "Fantasy"], description: "Wednesday Addams investigates a murder spree at Nevermore Academy.", poster: P.portrait10, backdrop: B.cinema2, seasons: 1 },
  { id: "last-of-us", title: "The Last of Us", type: "tv", embedId: "100088", year: 2023, rating: "8.7", duration: "1 Season", genres: ["Action", "Adventure", "Drama"], description: "A hardened survivor takes charge of a girl who may be humanity's last hope.", poster: P.horror6, backdrop: B.fog1, seasons: 1 },
  { id: "better-call-saul", title: "Better Call Saul", type: "tv", embedId: "60059", year: 2015, rating: "8.9", duration: "6 Seasons", genres: ["Crime", "Drama"], description: "The story of Jimmy McGill before he became Breaking Bad's Saul Goodman.", poster: P.portrait14, backdrop: B.city1, seasons: 6 },
  { id: "the-crown", title: "The Crown", type: "tv", embedId: "64016", year: 2016, rating: "8.7", duration: "6 Seasons", genres: ["Drama", "History"], description: "The political rivalries and romance of Queen Elizabeth II's reign.", poster: P.retro2, backdrop: B.cinema1, seasons: 6 },
  { id: "mandalorian", title: "The Mandalorian", type: "tv", embedId: "82856", year: 2019, rating: "8.7", duration: "3 Seasons", genres: ["Action", "Adventure", "Sci-Fi"], description: "A bounty hunter in the outer reaches of the galaxy protects a mysterious child.", poster: P.astronaut4, backdrop: B.space1, seasons: 3 },
  { id: "house-dragon", title: "House of the Dragon", type: "tv", embedId: "120168", year: 2022, rating: "8.4", duration: "2 Seasons", genres: ["Action", "Drama", "Fantasy"], description: "The Targaryen civil war, set 200 years before Game of Thrones.", poster: P.flame1, backdrop: B.cinema2, seasons: 2 },
  { id: "arcane", title: "Arcane", type: "tv", embedId: "94626", year: 2021, rating: "9.0", duration: "2 Seasons", genres: ["Action", "Adventure", "Animation"], description: "The origins of iconic League of Legends champions in Piltover and Zaun.", poster: P.portrait12, backdrop: B.city3, seasons: 2 },
  { id: "dark", title: "Dark", type: "tv", embedId: "71712", year: 2017, rating: "8.7", duration: "3 Seasons", genres: ["Crime", "Drama", "Sci-Fi"], description: "A missing child sets four families on a frantic hunt for answers.", poster: P.noir3, backdrop: B.fog2, seasons: 3 },
  { id: "westworld", title: "Westworld", type: "tv", embedId: "66057", year: 2016, rating: "8.5", duration: "4 Seasons", genres: ["Drama", "Mystery", "Sci-Fi"], description: "A futuristic theme park populated by artificial beings.", poster: P.astronaut3, backdrop: B.space2, seasons: 4 },
  { id: "black-mirror", title: "Black Mirror", type: "tv", embedId: "42009", year: 2011, rating: "8.7", duration: "6 Seasons", genres: ["Drama", "Sci-Fi", "Thriller"], description: "Anthology series exploring the dark side of technology.", poster: P.portrait9, backdrop: B.city1, seasons: 6 },
  { id: "money-heist", title: "Money Heist", type: "tv", embedId: "71446", year: 2017, rating: "8.2", duration: "5 Seasons", genres: ["Action", "Crime", "Drama"], description: "A criminal mastermind leads a group of robbers in heists across Spain.", poster: P.portrait7, backdrop: B.city2, seasons: 5 },
  { id: "suits", title: "Suits", type: "tv", embedId: "40511", year: 2011, rating: "8.4", duration: "9 Seasons", genres: ["Comedy", "Drama"], description: "A brilliant college dropout joins a top law firm despite no degree.", poster: P.portrait5, backdrop: B.city3, seasons: 9 },
  { id: "vikings", title: "Vikings", type: "tv", embedId: "60251", year: 2013, rating: "8.5", duration: "6 Seasons", genres: ["Action", "Adventure", "Drama"], description: "The saga of Ragnar Lothbrok and his Viking raids across England.", poster: P.soldier5, backdrop: B.mountain1, seasons: 6 },
  { id: "the-office", title: "The Office", type: "tv", embedId: "2316", year: 2005, rating: "9.0", duration: "9 Seasons", genres: ["Comedy"], description: "A mockumentary about the everyday lives of office employees.", poster: P.retro1, backdrop: B.cinema1, seasons: 9 },
  { id: "mr-robot", title: "Mr. Robot", type: "tv", embedId: "62560", year: 2015, rating: "8.5", duration: "4 Seasons", genres: ["Crime", "Drama", "Thriller"], description: "A cyber-security engineer becomes involved with an underground hacker group.", poster: P.portrait16, backdrop: B.city2, seasons: 4 },
  { id: "sherlock", title: "Sherlock", type: "tv", embedId: "19885", year: 2010, rating: "9.1", duration: "4 Seasons", genres: ["Crime", "Drama", "Mystery"], description: "A modern update of the classic detective stories.", poster: P.portrait1, backdrop: B.fog1, seasons: 4 },
  { id: "true-detective", title: "True Detective", type: "tv", embedId: "2356", year: 2014, rating: "8.9", duration: "4 Seasons", genres: ["Crime", "Drama", "Mystery"], description: "An anthology series following different crime investigations.", poster: P.horror5, backdrop: B.fog2, seasons: 4 },
  { id: "fargo-tv", title: "Fargo", type: "tv", embedId: "60043", year: 2014, rating: "8.9", duration: "5 Seasons", genres: ["Crime", "Drama", "Thriller"], description: "An anthology series inspired by the Coen Brothers film.", poster: P.horror1, backdrop: B.fog1, seasons: 5 },
  { id: "the-sopranos", title: "The Sopranos", type: "tv", embedId: "1418", year: 1999, rating: "9.2", duration: "6 Seasons", genres: ["Crime", "Drama"], description: "A New Jersey mob boss balances family life with his criminal empire.", poster: P.portrait6, backdrop: B.cinema1, seasons: 6 },
  { id: "band-of-brothers", title: "Band of Brothers", type: "tv", embedId: "4612", year: 2001, rating: "9.4", duration: "1 Season", genres: ["Drama", "History", "War"], description: "The story of Easy Company's paratroopers in WWII.", poster: P.soldier2, backdrop: B.mountain2, seasons: 1 },
  { id: "chernobyl", title: "Chernobyl", type: "tv", embedId: "87108", year: 2019, rating: "9.3", duration: "1 Season", genres: ["Drama", "History", "Thriller"], description: "The story of the 1986 nuclear disaster and its aftermath.", poster: P.smoke1, backdrop: B.fog2, seasons: 1 },
  { id: "the-wire", title: "The Wire", type: "tv", embedId: "1438", year: 2002, rating: "9.3", duration: "5 Seasons", genres: ["Crime", "Drama", "Thriller"], description: "The Baltimore drug scene through the eyes of law enforcement.", poster: P.noir2, backdrop: B.city3, seasons: 5 },
  { id: "lost", title: "Lost", type: "tv", embedId: "4667", year: 2004, rating: "8.3", duration: "6 Seasons", genres: ["Adventure", "Drama", "Mystery"], description: "Survivors of a plane crash must work together to stay alive on a mysterious island.", poster: P.mountain5, backdrop: B.mountain1, seasons: 6 },
  { id: " Narcos", title: "Narcos", type: "tv", embedId: "63351", year: 2015, rating: "8.8", duration: "3 Seasons", genres: ["Biography", "Crime", "Drama"], description: "The rise and fall of Colombian drug lord Pablo Escobar.", poster: P.portrait17, backdrop: B.city2, seasons: 3 },
];

export const CONTENT_MAP: Record<string, ContentItem> = Object.fromEntries(
  CATALOG.map((item) => [item.id, item])
);

export interface RowDef {
  title: string;
  filter: (item: ContentItem) => boolean;
}

export const ROWS: RowDef[] = [
  { title: "Trending Now", filter: () => true },
  { title: "John Wick Collection", filter: (i) => i.title.toLowerCase().includes("john wick") },
  { title: "Marvel Cinematic Universe", filter: (i) => ["avengers", "iron man", "captain america", "thor", "guardians", "black panther", "spider-man"].some(k => i.title.toLowerCase().includes(k)) },
  { title: "Christopher Nolan Films", filter: (i) => ["inception", "interstellar", "tenet", "memento", "prestige", "batman begins", "dark knight", "dunkirk", "following", "oppenheimer"].some(k => i.title.toLowerCase().includes(k)) },
  { title: "Tarantino Collection", filter: (i) => ["pulp fiction", "django", "kill bill", "inglourious", "hateful", "once upon"].some(k => i.title.toLowerCase().includes(k)) },
  { title: "Scorsese Classics", filter: (i) => ["goodfellas", "taxi driver", "casino", "departed", "shutter", "irishman", "wolf of wall"].some(k => i.title.toLowerCase().includes(k)) },
  { title: "Sci-Fi & Beyond", filter: (i) => i.genres.some(g => ["Sci-Fi", "Fantasy"].includes(g)) },
  { title: "Action Blockbusters", filter: (i) => i.genres.includes("Action") && i.type === "movie" },
  { title: "Crime & Thrillers", filter: (i) => i.genres.some(g => ["Crime", "Thriller", "Mystery"].includes(g)) },
  { title: "Horror Picks", filter: (i) => i.genres.includes("Horror") },
  { title: "Animated & Family", filter: (i) => i.genres.some(g => ["Animation", "Family"].includes(g)) },
  { title: "Critically Acclaimed", filter: (i) => parseFloat(i.rating) >= 8.5 },
  { title: "Popular Series", filter: (i) => i.type === "tv" },
];

export const FEATURED = CATALOG.find((item) => item.featured) ?? CATALOG[0];
